var m=(s,e,t)=>{if(!e.has(s))throw TypeError("Cannot "+t)};var i=(s,e,t)=>(m(s,e,"read from private field"),t?t.call(s):e.get(s)),d=(s,e,t)=>{if(e.has(s))throw TypeError("Cannot add the same private member more than once");e instanceof WeakSet?e.add(s):e.set(s,t)};import{a as c}from"./assets/vendor-26fe51b3.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))n(o);new MutationObserver(o=>{for(const r of o)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function t(o){const r={};return o.integrity&&(r.integrity=o.integrity),o.referrerpolicy&&(r.referrerPolicy=o.referrerpolicy),o.crossorigin==="use-credentials"?r.credentials="include":o.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(o){if(o.ep)return;o.ep=!0;const r=t(o);fetch(o.href,r)}})();var l;class h{constructor(e,t){d(this,l,"https://books-backend.p.goit.global/");this.selectedCategory=e,this.bookId=t}fetchBooksCategoryList(){return c.get(`${i(this,l)}books/category-list`)}fetchBestSellersBooks(){return c.get(`${i(this,l)}books/top-books`)}fetchBooksByCategory(e){return c.get(`${i(this,l)}books/category?category=${e}`)}fetchBookById(e){return c.get(`${i(this,l)}books/${e}`)}}l=new WeakMap;const u=document.querySelector(".best-sellers-books"),f=new h;g();async function g(){return await f.fetchBestSellersBooks().then(e=>e.data.map(t=>{const n=t.books.map(o=>`<li class="best-sellers-book" data-book-id="${o._id}">
             <img class="best-sellers-book-img" src="${o.book_image}" alt="${o.title}" />
             <p class="best-sellers-book-title">${o.title}</p>
             <p class="best-sellers-book-author">${o.author}</p>
</li>`).join("");u.insertAdjacentHTML("beforeend",`<li class="best-seller-category"> 
                <p class="category-title"> ${t.list_name} </p> 
                <ul class="best-sellers-list-in-category">
                ${n} 
                </ul> 
                <button type="button" class="best-sellers-see-more-button" data-button-category-name="${t.list_name}">See more</button>
                    </li>`)}).join("")).catch(e=>{console.log(e.message),u.innerHTML="No information"})}const b={btn:document.querySelector(".scrollBtn"),show(){this.btn.classList.remove("scrollBtn-hide")},hide(){this.btn.classList.add("scrollBtn-hide")},addEventListener(){this.btn&&(window.addEventListener("scroll",()=>{(window.scrollY||document.documentElement.scrollTop)>100?this.show():this.hide()}),this.btn.onclick=()=>{window.scrollTo({top:0,behavior:"smooth"})})}};b.addEventListener();const p=document.querySelector(".category");function y(s){s.sort((t,n)=>t.list_name.localeCompare(n.list_name));const e=s.map(t=>{const{list_name:n}=t;return`<li><a class='genre' href="#" target="_self">${n}</a></li>`}).join("");p.insertAdjacentHTML("beforeend",e)}function k(){new h().fetchBooksCategoryList().then(e=>{const t=e.data;console.log(t),y(t)}).catch(e=>{console.error(e)})}k();const L=document.getElementById("themeSwitch");L.addEventListener("change",B);function B(){const s=document.body;s.classList.toggle("light-theme"),s.classList.toggle("dark-theme")}
//# sourceMappingURL=commonHelpers.js.map
