var b=(o,e,s)=>{if(!e.has(o))throw TypeError("Cannot "+s)};var n=(o,e,s)=>(b(o,e,"read from private field"),s?s.call(o):e.get(o)),d=(o,e,s)=>{if(e.has(o))throw TypeError("Cannot add the same private member more than once");e instanceof WeakSet?e.add(o):e.set(o,s)};import{a as c}from"./assets/vendor-26fe51b3.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerpolicy&&(r.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?r.credentials="include":t.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();var l;class h{constructor(e,s){d(this,l,"https://books-backend.p.goit.global/");this.selectedCategory=e,this.bookId=s}fetchBooksCategoryList(){return c.get(`${n(this,l)}books/category-list`)}fetchBestSellersBooks(){return c.get(`${n(this,l)}books/top-books`)}fetchBooksByCategory(e){return c.get(`${n(this,l)}books/category?category=${e}`)}fetchBookById(e){return c.get(`${n(this,l)}books/${e}`)}}l=new WeakMap;const u=document.querySelector(".best-sellers-books"),f=new h;m();async function m(){return await f.fetchBestSellersBooks().then(e=>e.data.map(s=>{const i=s.books.map(t=>`<li class="best-sellers-book" data-book-id="${t._id}">
             <img class="best-sellers-book-img" src="${t.book_image}" alt="${t.title}" />
             <p class="best-sellers-book-title">${t.title}</p>
             <p class="best-sellers-book-author">${t.author}</p>
</li>`).join("");u.insertAdjacentHTML("beforeend",`<li class="best-seller-category"> 
                <p class="category-title"> ${s.list_name} </p> 
                <ul class="best-sellers-list-in-category">
                ${i} 
                </ul> 
                <button type="button" class="best-sellers-see-more-button" data-button-category-name="${s.list_name}">See more</button>
                    </li>`)}).join("")).catch(e=>{console.log(e.message),u.innerHTML="No information"})}const g={btn:document.querySelector(".scrollBtn"),show(){this.btn.classList.remove("scrollBtn-hide")},hide(){this.btn.classList.add("scrollBtn-hide")},addEventListener(){this.btn&&(window.addEventListener("scroll",()=>{(window.scrollY||document.documentElement.scrollTop)>100?this.show():this.hide()}),this.btn.onclick=()=>{window.scrollTo({top:0,behavior:"smooth"})})}};g.addEventListener();
//# sourceMappingURL=commonHelpers.js.map
