var p=(s,e,t)=>{if(!e.has(s))throw TypeError("Cannot "+t)};var c=(s,e,t)=>(p(s,e,"read from private field"),t?t.call(s):e.get(s)),m=(s,e,t)=>{if(e.has(s))throw TypeError("Cannot add the same private member more than once");e instanceof WeakSet?e.add(s):e.set(s,t)};/* empty css                      */import{a as i}from"./assets/vendor-26fe51b3.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))n(o);new MutationObserver(o=>{for(const r of o)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function t(o){const r={};return o.integrity&&(r.integrity=o.integrity),o.referrerpolicy&&(r.referrerPolicy=o.referrerpolicy),o.crossorigin==="use-credentials"?r.credentials="include":o.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(o){if(o.ep)return;o.ep=!0;const r=t(o);fetch(o.href,r)}})();var l;class g{constructor(e,t){m(this,l,"https://books-backend.p.goit.global/");this.selectedCategory=e,this.bookId=t}fetchBooksCategoryList(){return i.get(`${c(this,l)}books/category-list`)}fetchBestSellersBooks(){return i.get(`${c(this,l)}books/top-books`)}fetchBooksByCategory(e){return i.get(`${c(this,l)}books/category?category=${e}`)}fetchBookById(e){return i.get(`${c(this,l)}books/${e}`)}}l=new WeakMap;const h=document.querySelector(".best-sellers-books"),y=new g;L();async function L(){return await y.fetchBestSellersBooks().then(e=>e.data.map(t=>{const n=t.books.map(o=>`<li class="best-sellers-book" data-book-id="${o._id}">
             <img class="best-sellers-book-img" src="${o.book_image}" alt="${o.title}" />
             <p class="best-sellers-book-title">${o.title}</p>
             <p class="best-sellers-book-author">${o.author}</p>
</li>`).join("");h.insertAdjacentHTML("beforeend",`<li class="best-seller-category"> 
                <p class="category-title"> ${t.list_name} </p> 
                <ul class="best-sellers-list-in-category">
                ${n} 
                </ul> 
                <button type="button" class="best-sellers-see-more-button" data-button-category-name="${t.list_name}">See more</button>
                    </li>`)}).join("")).catch(e=>{console.log(e.message),h.innerHTML="No information"})}const k={btn:document.querySelector(".scrollBtn"),show(){this.btn.classList.remove("scrollBtn-hide")},hide(){this.btn.classList.add("scrollBtn-hide")},addEventListener(){this.btn&&(window.addEventListener("scroll",()=>{(window.scrollY||document.documentElement.scrollTop)>100?this.show():this.hide()}),this.btn.onclick=()=>{window.scrollTo({top:0,behavior:"smooth"})})}};k.addEventListener();const S=document.querySelector(".category");function v(s){s.sort((t,n)=>t.list_name.localeCompare(n.list_name));const e=s.map(t=>{const{list_name:n}=t;return`<li><a class='genre' href="#" target="_self">${n}</a></li>`}).join("");S.insertAdjacentHTML("beforeend",e)}function B(){new g().fetchBooksCategoryList().then(e=>{const t=e.data;console.log(t),v(t)}).catch(e=>{console.error(e)})}B();const d=document.querySelector(".header-modal"),$=document.querySelector(".modal-open-btn"),f=document.querySelector("body"),u=document.querySelector(".open-icon");console.dir(u.innerHTML);$.addEventListener("click",w);function w(s){if(d.classList.contains("hidden-modal")){d.classList.remove("hidden-modal"),f.classList.add("stop-scrolling"),u.innerHTML='<use href="./img/sprit.svg#x-close"/>';return}else d.classList.add("hidden-modal"),f.classList.remove("stop-scrolling"),u.innerHTML='<use href="./img/sprit.svg#icon-burger"/>'}const q=document.querySelector(":root"),b=document.querySelector("#themeSwitch");b.addEventListener("change",E);function E(){event.preventDefault(),q.classList.toggle("dark-theme",b.checked)}
//# sourceMappingURL=commonHelpers.js.map
